---
- name: Bootloader cgroup params
  register: bootloader_cgroup
  become: yes
  become_user: root
  replace:
    path: /boot/cmdline.txt
    regexp: 'rootwait$'
    replace: 'rootwait cgroup_memory=1 cgroup_enable=memory'

- name: Bootloader change reboot
  reboot:
  become: yes
  become_user: root
  when: bootloader_cgroup is changed

- name: Add ca cert
  become: yes
  become_user: root
  copy:
    src: "{{ role_path }}/files/ca.crt"
    dest: /usr/local/share/ca-certificates/ca.crt
    mode: 0644
  register: add_ca_cert_to_trust

- name: Update ca certificates
  become: yes
  become_user: root
  command: update-ca-certificates
  when: add_ca_cert_to_trust.changed

- name: Install vim
  become: yes
  become_user: root
  ansible.builtin.apt:
    name: vim
    state: present

- name: Manage host file
  become: yes
  become_user: root
  template:
    src: "{{ role_path }}/files/hosts"
    dest: /etc/hosts
    mode: 0644